# -*- coding: utf-8 -*-
"""Student performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjVMxKiKAB4FxqseziBxlyKPCeCb3jaZ
"""

import pandas as pd
import matplotlib.pyplot as plt

#Read Excel file
df = pd.read_excel("student_performance_data.xlsx")


#Display dataset
print("Student Dataset")
print(df)

#Statistical Summary
print(df.describe())